# This file exports functionality used to create projects with the given layout and ensure they have been created.

set(EZCMK_PROJECT_INCLUDE_PATH "include")
set(EZCMK_PROJECT_PRECOMPILED_HEADER_PATH "/${EZCMK_PROJECT_INCLUDE_PATH}/")
set(EZCMK_PROJECT_SRC_PATH "src")

#[[.rst:
.. command:: EzCMK_CreateTarget

   Creates a target if it didn't exist.

   **Arguments:**
   - ``NAME`` (required): The name of the target.
   - ``PRECOMPILED_HEADER`` (optional): Path to a precompiled header.
   - ``TARGET_DIR_PATH``: Path to where the project should be (including NAME).
   - ``FILE_LIST`` (required): Source files.
   - ``INCLUDED_DIRS`` (optional): Extra include directories.

   Example::

       EzCMK_CreateTarget(
           NAME MyTarget
           FILE_LIST ${TARGET_FILE_LIST}
           INCLUDED_DIRS "include"
           PRECOMPILED_HEADER Common.h
       )
]]

#[[.CLION_DOC:
* @brief Retrieves the current library build type
* @param OUT_VAR (required) Output variable name
* @param FORCE_VALUE (optional) Override the stored value
* @return Sets ${OUT_VAR} to the build type string
.CLION_DOC]]
function(EzCMK_CreateTarget)
    set(options)  # no boolean switches
    set(oneValueArgs NAME PRECOMPILED_HEADER TARGET_DIR_PATH)
    set(multiValueArgs FILE_LIST INCLUDED_DIRS)
    cmake_parse_arguments("ARG" "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    message(STATUS "Creating target: ${ARG_NAME} at ${ARG_TARGET_DIR_PATH}")

    set(TARGET_PATH "${ARG_TARGET_DIR_PATH}")
    set(INCLUDE_DIRECTORY "${TARGET_PATH}/${EZCMK_PROJECT_INCLUDE_PATH}")
    set(SRC_DIRECTORY "${TARGET_PATH}/${EZCMK_PROJECT_SRC_PATH}")
    set(CMAKELISTS "${ARG_TARGET_DIR_PATH}/CMakeLists.txt")

    if (DEFINED ARG_WAS_CREATED)
        set(${ARG_WAS_CREATED} OFF PARENT_SCOPE)
    endif ()

    if (NOT IS_DIRECTORY ${TARGET_PATH})
        message(STATUS "Creating target's directory")
        file(MAKE_DIRECTORY "${TARGET_PATH}")
    else ()
        message(STATUS "Target's directory already created")
    endif ()

    if (NOT IS_DIRECTORY "${INCLUDE_DIRECTORY}")
        message(STATUS "Creating target's include directory: ${INCLUDE_DIRECTORY}")
        file(MAKE_DIRECTORY "${INCLUDE_DIRECTORY}")
    else ()
        message(STATUS "Target's include directory already created")
    endif ()

    if (NOT IS_DIRECTORY "${SRC_DIRECTORY}")
        message(STATUS "Creating target's src directory: ${SRC_DIRECTORY}")
        file(MAKE_DIRECTORY "${SRC_DIRECTORY}")
    else ()
        message(STATUS "Target's src directory already created")
    endif ()

    if (NOT EXISTS "${CMAKELISTS}")
        message(STATUS "Creating target's CMakeLists: ${CMAKELISTS}")
        file(WRITE "${CMAKELISTS}" "# Generated by EzCMK")

        # This is the configuring file, if this was not present we can consider we created the project.
        if (DEFINED ARG_WAS_CREATED)
            set(${ARG_WAS_CREATED} ON PARENT_SCOPE)
        endif ()

    else ()
        message(STATUS "CMakeLists.txt already created")
    endif ()

    # Project name is appended to the #if-guard to ensure this header is unique across the entire workspace.
    if ((DEFINED ARG_PRECOMPILED_HEADER) AND (NOT EXISTS "${ARG_PRECOMPILED_HEADER}"))
        message(STATUS "Creating target's precompiled header: ${ARG_PRECOMPILED_HEADER}")
        file(WRITE "${ARG_PRECOMPILED_HEADER}" "
#ifndef ${CMAKE_PROJECT_NAME}_${NAME}_PRECOMPILED_HEADER_H
#define ${CMAKE_PROJECT_NAME}_${NAME}_PRECOMPILED_HEADER_H

// Generated by EzCMK

#endif")
    else ()
        message(STATUS "Precompiled header already created")
    endif ()

endfunction()